version: '3'

services:
  # app:
  #   image: node:14-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #   command: ['yarn', 'start:dev']
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mongo:
    image: mongo
    ports:
      - 27018:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
    volumes:
      - ./mongo:/data/db